<?php

use Illuminate\Database\Seeder;
use App\Instituicao;

class InstituicoesSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Instituicao::insert([ 
            ['nome'=>'ESCOLA MUNICIPAL AQUILINO DA MOTA DUARTE',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL ARCO IRIS',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL BRANCA DE NEVE',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL CANTINHO DO CÉU',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL CANTINHO FELIZ',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL CENTENARIO DE BOA VISTA',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL CRIANÇA FELIZ',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL CUNHATÃ CURUMIM',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL DALÍCIO FARIAS FILHO',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL DELACIR DE MELO LIMA',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL DOUTOR SILVIO LEITE',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL ESTRELINHA MAGICA',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL FRANSCISCO CASSIO DE MORAES',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL FRANCISCO DE SOUZA BRIGLIA',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL FREI ARTHUR AGOSTIN',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL HILDA FRANCO DE SOUZA',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL IOLÁDIO BATISTA DA SILVA',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL ISETE EVANGELISTA ALBUQUERQUE',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL JAEL DA SILVA BARRADAS',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICILA JÂNIO DA SILVA QUADROS',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL JARDIM DAS COPAIBAS',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL JOSÉ ARNÓBIO DA SILVA',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL JÓQUEI CLUBE',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL JUSLANY DE SOUZA FLORES',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL LAUCIDES INÁCIO DE OLIVEIRA',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL LUIZ CANARÁ',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL MARIA DE FÁTIMA FARIA ANDRADE',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL MARIA GONÇALVES VIEIRA',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL MARIA TERESA MACIEL DA SILVEIRA MELO',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL MARTINHA THURY VIEIRA',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL MENINO DE JESUS',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL MENINO JESUS DE PRAGA',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL NEWTON TAVARES',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL NOVA CANAÃ',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL PALMIRA CASTR O MACHADO',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL PEQUENO POLEGAR',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL PEQUENO PRINCIPE',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL PINGO DE GENTE',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL PROFESSOR CARLOS RAIMUNDO RODRIGUES',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL PROFESSORA AMAZONA DE OLIVEIRA MONTEIRO',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL PROFESSORA ANA SANDRA NASCIMENTO QUEIROZ',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL PROFESSORA ANTONIA FERNANDES CUTRIM',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL PROFESSORA CARMEM EUGÊNIA MACAGGI',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL PROFESSORA DANÚBIA CARVALHO DE OLIVEIRA',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL PROFESSORA EDSONINA DE NARROS VILLA',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL PROFESSORA GLEMÍRIA GONZAGA ANDRADE',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL PROFESSORA IVANY DOS SANTOS PARENTE',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL PROFESSORA MARIA FRANCISCA DA SILVA LEMOS',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL PROFESSORA MARIA GERTRUDES MOTA DE LIMA',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL RAIMUNDO ELOY GOMES',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL RAIO DE SOL',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL RUJANE SEVERIANO DOS SANTOS',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL SENADOR DARCY RIBEIRO',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL SONHO INFANTIL',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL TIA LINDA',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL VALDEMARINA NORMANDO MARTINS',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL VOVO CLARA',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL VOVO DANDAE',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL VOVO EURIDES',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL VOVO JULIA',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL ZACARIAS ASSUNÇÃO RIBEIRO ARAUJO',  'tipo_id'=>1],
                ['nome'=>'ESCOLA MUNICIPAL ALDO TORREIAS DO NASCIMENTO',  'tipo_id'=>2],
                ['nome'=>'ESCOLA MUNICIPAL PROFESSORA AUREA DE HOLANDA LIMA',  'tipo_id'=>2],
                ['nome'=>'ESCOLA MUNICIPAL ANTONIO AIRTON OLIVEIRA DIAS',  'tipo_id'=>2],
                ['nome'=>'ESCOLA MUNICIPAL JAMES MACELARO THOMÉ',  'tipo_id'=>2],
                ['nome'=>'ESCOLA MUNICIPAL MARIA DO PERPETUO SOCORRO FREIRE BRANDÃO',  'tipo_id'=>2],
                ['nome'=>'ESCOLA MUNICIPAL VILA JARDIM',  'tipo_id'=>2],
                ['nome'=>'ESCOLA MUNICIPAL VALDERLEIDE VARA[UNA BRANDÃO',  'tipo_id'=>2],
                ['nome'=>'ESCOLA MUNICIPAL WALDINETE DE CARVALHO CHAVES',  'tipo_id'=>2],
                ['nome'=>'NÚCLEO NOVA CIDADE - NOVA VIDADE',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO NOVA CIDADE - NOVA VIDADE I',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO NOVA CIDADE - NOVA VIDADE II',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO BELA VISTA - PRISCILA MIRIAN GALVÃO ALMEIDA',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO BELA VISTA - BELA VISTA',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO RAIAR DO SOL - RAIAR DO SOL',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO RAIAR DO SOL - MUNDO ENCANTADO',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO CENTENÁRIO - FLOR DO CAMPO',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO CENTENÁRIO - LAGOA ENCANTADA',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO CENTENÁRIO - RECANTO DO AMOR',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO PINTOLÂNCIA - VOVÓ JOANA',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO PINTOLÂNCIA - VOVÓ SEVERINA',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO PINTOLÂNCIA - VOVÓ WANDA',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO PINTOLÂNCIA - VOVÓ ELENIR',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO SENADOR HELIO CAMPOS - TIA RAY',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO SENADOR HELIO CAMPOS - TIA LIDIA',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO SENADOR HELIO CAMPOS - SENADOR I',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO SENADOR HELIO CAMPOS - SENADOR II',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO ALVORADA - VOVÓ FRANCISCA',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO ALVORADA - VOVOZINHA ALTAÍDE',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO EQUATORIAL - VOVÓ ROSA',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO EQUATORIAL - TIA NEIDE',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO EQUATORIAL - LUZ DO SOL',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO CIDADE SATÉLITE I - VOVÓ CONCEIÇÃO',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO CIDADE SATÉLITE I - VOVÓ JOANA CIDADE',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO CIDADE SATÉLITE I - PEDACINHO DE GENTE',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO CIDADE SATÉLITE II',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO CIDADE SATÉLITE II - DINHÁ LARANJEIRA',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO CIDADE SATÉLITE II - TIA LOURDES',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO JARDIM CARANÃ - TIA ÁUREA',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO JARDIM CARANÃ - VOVÓ ELZA MESQUITA',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO CIDADÃO - TIA DULCE',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO CIDADÃO - TIA HERIKA',  'tipo_id'=>3],
                ['nome'=>'NÚCLEO CIDADÃO - BRILHA ESTRELINHA',  'tipo_id'=>3],
                ['nome'=>'ESCOLA MUNICIPAL INDÍGENA CLEMENTE DOS SANTOS',  'tipo_id'=>4],
                ['nome'=>'ESCOLA MUNICIPAL INDÍGENA DUKUZYY SEBASTIÃO',  'tipo_id'=>4],
                ['nome'=>'ESCOLA MUNICIPAL INDÍGENA IGNÊS BENEDICTO',  'tipo_id'=>4],
                ['nome'=>'ESCOLA MUNICIPAL INDÍGENA MARTINS PEREIRA DA SILVA',  'tipo_id'=>4],
                ['nome'=>'ESCOLA MUNICIPAL INDÍGENA FRANCISCA GOMES DA SILVA',  'tipo_id'=>4],
                ['nome'=>'ESCOLA MUNICIPAL INDÍGENA TUXAUA ALBINO MORAIS',  'tipo_id'=>4],
                ['nome'=>'ESCOLA MUNICIPAL INDÍGENA KO’KO ERMELINDA RAPOSO DA SILVA',  'tipo_id'=>4],
                ['nome'=>'ESCOLA MUNICIPAL INDÍGENA VOVÓ TEREZINHA DA SILVA',  'tipo_id'=>4],
                ['nome'=>'ESCOLA MUNICIPAL INDÍGENA VOVÓ TEREZA DA SILVA',  'tipo_id'=>4],
                ['nome'=>'ESCOLA MUNICIPAL INDÍGENA VICENTE ANDRÉ DA SILVA',  'tipo_id'=>4],
                ['nome'=>'ESCOLA MUNICIPAL INDÍGENA VOVÓ ANTÔNIA CELESTINA DA SILVA',  'tipo_id'=>4],
                ['nome'=>'ESCOLA MUNICIPAL INDÍGENA VOVÔ JANDICO DA SILVA',  'tipo_id'=>4],
                ['nome'=>'ESCOLA MUNICIPAL BALDUÍNO WOTTRICH',  'tipo_id'=>5],
                ['nome'=>'ESCOLA MUNICIPAL MARIA DE LOURDES DIAS DE ABREU',  'tipo_id'=>5],
                ['nome'=>'ESCOLA MUNICIPAL LEILA MARIA DA SILVEIRA',  'tipo_id'=>5],
                ['nome'=>'ESCOLA MUNICIPAL JOSÉ DAVID FEITOSA NETO',  'tipo_id'=>5],
                ['nome'=>'ESCOLA MUNICIPAL AURELIANO SOARES DA SILVA',  'tipo_id'=>5],
                ['nome'=>'SECRETÁRIA MUNICIPAL DE EDUCAÇÃO E CULTURA - SMEC',  'tipo_id'=>6],
                ['nome'=>'SUPERINTENDÊNCIA DE EDUCAÇÃO BÁSICA - SEB',  'tipo_id'=>6],
                ['nome'=>'SUPERINTENDÊNCIA DE PLANEJAMENTO EDUCACIONAL- SPE',  'tipo_id'=>6],
                ['nome'=>'SUPERINTENDÊNCIA DE ADMINISTRAÇÃO E GESTÃO DE PESSOAS - SUAGEP',  'tipo_id'=>6],
                ['nome'=>'SUPERINTENDÊNCIA DE ADMINISTRAÇÃO - SUAD',  'tipo_id'=>6]
         ]);
    }
}
